### ISSUE TITLE
Implement logic to smooth snow accumulation

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/WinterWonderLand#2]
@KnightMiner suggests to only allow a layer to be added if 2 neighbor blocks are already at that height.

I might want to add a few different algorithms for different appearances.

**Comment by KnightMiner** [comment]
Oh, cool. Might be good to also treat solid blocks as a height of 8, just so snow will more easily form on hills.

**Comment by cam72cam** [comment]
I'll probably tackle that in https://github.com/cam72cam/WinterWonderLand/issues/3
