### ISSUE TITLE
[1.12.1] Raining Error

### ISSUE THREAD

**Issue by Preminenc3** [cam72cam/WinterWonderLand#6]
Seems like no matter what biome if downfall is enabled then snow will build up, even if it's not snow in every biome. Sometimes spawns on water, usually near the edge of blocks.

**Comment by cam72cam** [comment]
Excellent bug report.  I'll put out a fix after work (an hour or so)

**Comment by cam72cam** [comment]
I missed the worldserver.canSnowAt call
